In [3]:
from pymongo import MongoClient
import pandas as pd

In [4]:
client = MongoClient("mongodb://localhost:27017/")
db = client["taller4_db"]
collection = db["raw_data"]
data = list(collection.find())

In [5]:
df = pd.DataFrame(data)
df.head()

,_id,flags,name,capital,region,subregion,area,population
0,6a2240d33992358a372b175e,"{'png': 'https://flagcdn.com/w320/ai.png', 'sv...","{'common': 'Anguilla', 'official': 'Anguilla',...",[The Valley],Americas,Caribbean,91.0,16010
1,6a2240d33992358a372b175f,"{'png': 'https://flagcdn.com/w320/gt.png', 'sv...","{'common': 'Guatemala', 'official': 'Republic ...",[Guatemala City],Americas,Central America,108889.0,18079810
2,6a2240d33992358a372b1760,"{'png': 'https://flagcdn.com/w320/gm.png', 'sv...","{'common': 'Gambia', 'official': 'Republic of ...",[Banjul],Africa,Western Africa,10689.0,2422712
3,6a2240d33992358a372b1761,"{'png': 'https://flagcdn.com/w320/mx.png', 'sv...","{'common': 'Mexico', 'official': 'United Mexic...",[Mexico City],Americas,North America,1964375.0,130575786
4,6a2240d33992358a372b1762,"{'png': 'https://flagcdn.com/w320/mw.png', 'sv...","{'common': 'Malawi', 'official': 'Republic of ...",[Lilongwe],Africa,Eastern Africa,118484.0,20734262

In [6]:
df = pd.DataFrame({
    "nombre": df["name"].apply(lambda x: x.get("common")),
    "poblacion": df["population"],
    "region": df["region"],
    "area": df["area"],
    "capital": df["capital"]
})

df.head()

      nombre  poblacion    region       area           capital
0   Anguilla      16010  Americas       91.0      [The Valley]
1  Guatemala   18079810  Americas   108889.0  [Guatemala City]
2     Gambia    2422712    Africa    10689.0          [Banjul]
3     Mexico  130575786  Americas  1964375.0     [Mexico City]
4     Malawi   20734262    Africa   118484.0        [Lilongwe]

In [7]:
df.head()

      nombre  poblacion    region       area           capital
0   Anguilla      16010  Americas       91.0      [The Valley]
1  Guatemala   18079810  Americas   108889.0  [Guatemala City]
2     Gambia    2422712    Africa    10689.0          [Banjul]
3     Mexico  130575786  Americas  1964375.0     [Mexico City]
4     Malawi   20734262    Africa   118484.0        [Lilongwe]

In [9]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 250 entries, 0 to 249
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   nombre     250 non-null    str
 1   poblacion  250 non-null    int64
 2   region     250 non-null    str
 3   area       250 non-null    float64
 4   capital    250 non-null    object
dtypes: float64(1), int64(1), object(1), str(2)
memory usage: 9.9+ KB

In [12]:
df.isnull().sum()

nombre       0
poblacion    0
region       0
area         0
capital      0
dtype: int64